export const LOCATION = "LOCATION";

export const BAG_INCREMENT = "BAG_INCREMENT";
export const BAG_DECREMENT = "BAG_DECREMENT";

export const BLENDER_INCREMENT = "BLENDER_INCREMENT";
export const BLENDER_DECREMENT = "BLENDER_DECREMENT";

export const PRESSING_IRON_INCREMENT = "PRESSING_IRON_INCREMENT";
export const PRESSING_IRON_DECREMENT = "PRESSING_IRON_DECREMENT";
